//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorilya.Framework.Core.Cache.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CacheMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CacheMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gorilya.Framework.Core.Cache.Resources.CacheMessages", typeof(CacheMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the Cache FIle..
        /// </summary>
        internal static string F_CCS_001 {
            get {
                return ResourceManager.GetString("F_CCS_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Serialise the Cache Data..
        /// </summary>
        internal static string F_CCS_002 {
            get {
                return ResourceManager.GetString("F_CCS_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve desired Caching Behaviour..
        /// </summary>
        internal static string F_CCS_003 {
            get {
                return ResourceManager.GetString("F_CCS_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Unknown Error occurred while attempting to store the Cache..
        /// </summary>
        internal static string F_CCS_004 {
            get {
                return ResourceManager.GetString("F_CCS_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Deserialise the Cache File..
        /// </summary>
        internal static string F_CCS_005 {
            get {
                return ResourceManager.GetString("F_CCS_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create old Cache File as an Archive..
        /// </summary>
        internal static string F_CCS_006 {
            get {
                return ResourceManager.GetString("F_CCS_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error was encountered while Processing..
        /// </summary>
        internal static string F_GenericMessage {
            get {
                return ResourceManager.GetString("F_GenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache File was created successfully..
        /// </summary>
        internal static string S_CCS_001 {
            get {
                return ResourceManager.GetString("S_CCS_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of HistoryStack updated successfully..
        /// </summary>
        internal static string S_CCS_002 {
            get {
                return ResourceManager.GetString("S_CCS_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find any existing cache, a new one was created successfully..
        /// </summary>
        internal static string S_CCS_003 {
            get {
                return ResourceManager.GetString("S_CCS_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing cache found and Deserialised successfully..
        /// </summary>
        internal static string S_CCS_004 {
            get {
                return ResourceManager.GetString("S_CCS_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed successfully..
        /// </summary>
        internal static string S_GenericMessage {
            get {
                return ResourceManager.GetString("S_GenericMessage", resourceCulture);
            }
        }
    }
}
